# Generated by Django 4.1.6 on 2024-02-15 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('cattegory_img', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='All_Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100)),
                ('food_img', models.ImageField(upload_to='')),
                ('food_price', models.FloatField()),
                ('food_desc', models.TextField()),
                ('food_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mozato_app.food_category')),
            ],
        ),
    ]
