# Generated by Django 4.1.6 on 2024-02-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozato_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_food',
            name='food_status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50, null=True),
        ),
    ]
